version: '3.7'

services:
        tor:
                container_name: tor
                image: lncm/tor:0.4.5.7@sha256:a83e0d9fd1a35adf025f2f34237ec1810e2a59765988dce1dfb222ca8ef6583c
                user: toruser
                restart: unless-stopped
                volumes:
                    - ${PWD}/tor/torrc:/etc/tor/torrc
                    - ${PWD}/tor/data:/var/lib/tor/
                    - ${PWD}/tor/run:/var/run/tor/
                ports:
                  - "127.0.0.1:9150:29050"
                networks:
                    net:
                        ipv4_address: ${TOR_PROXY_IP}
        nginx:
                container_name: nginx
                image: nginx:1.17.8@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03
                depends_on: [ dashboard, manager ]
                volumes:
                        - ${PWD}/nginx:/etc/nginx
                restart: unless-stopped
                stop_grace_period: 30s
                ports:
                    - "80:80"
                networks:
                    net:
                        ipv4_address: ${NGINX_IP}
        bitcoin:
                container_name: bitcoin
                image: lncm/bitcoind:v0.21.1@sha256:5bedb46d698de16c59e9e43d31485d0d82239bd437d62ac7cf47ebb633214f37
                depends_on: [ tor, manager ]
                command: "-zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333"
                volumes:
                        - ${PWD}/bitcoin:/data/.bitcoin
                restart: unless-stopped
                stop_grace_period: 15m30s
                ports:
                    - "8333:8333"
                networks:
                    net:
                        ipv4_address: ${BITCOIN_IP}
        lnd:
                container_name: lnd
                image: lightninglabs/lnd:v0.13.1-beta
                depends_on: [ tor, manager ]
                volumes:
                        - ${PWD}/lnd:/root/.lnd
                        - ${PWD}/walletpassword:/walletpassword
                restart: unless-stopped
                stop_grace_period: 5m30s
                ports:
                    - "9735:9735"
                networks:
                    net:
                        ipv4_address: ${LND_IP}
        dashboard:
                container_name: dashboard
                image: getumbrel/dashboard:v0.3.22@sha256:144105c0b7b6717f22e18171eec481897bb96344c7c298c681c9c04ce2b764a6
                restart: unless-stopped
                stop_grace_period: 1m30s
                networks:
                    net:
                        ipv4_address: ${DASHBOARD_IP}
        manager:
                container_name: manager
                image: communitybitcoinnode/manager:main@sha256:d748a84c2a840a8883eab912c605ba0579bdbacace6a75220f0406f4a00b1688
                depends_on: [ tor ]
                restart: unless-stopped
                stop_grace_period: 5m30s
                volumes:
                        - ${PWD}:${PWD}
                        - ${PWD}/info.json:/info.json
                        - ${PWD}/db:/db
                        - ${PWD}/events/signals:/signals
                        - ${PWD}/apps:/apps
                        - ${PWD}/statuses:/statuses
                        - ${PWD}/tor/data:/var/lib/tor/
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/bin/docker:/usr/bin/docker
                        - jwt-public-key:/jwt-public-key
                        - jwt-private-key:/jwt-private-key
                        - ${PWD}/lnd:/lnd:ro
                environment:
                    PORT: "3006"
                    USER_PASSWORD_FILE: "/db/user.json"
                    JWT_PUBLIC_KEY_FILE: "/jwt-public-key/jwt.pem"
                    JWT_PRIVATE_KEY_FILE: "/jwt-private-key/jwt.key"
                    JWT_EXPIRATION: "3600"
                    DOCKER_COMPOSE_DIRECTORY: $PWD
                    DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
                    DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-""}
                    MIDDLEWARE_API_URL: "http://${MIDDLEWARE_IP}"
                    SEED_FILE: "/db/umbrel-seed/seed"
                    DASHBOARD_HIDDEN_SERVICE_FILE: "/var/lib/tor/web/hostname"
                    BITCOIN_P2P_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-p2p/hostname"
                    BITCOIN_P2P_PORT: $BITCOIN_P2P_PORT
                    BITCOIN_RPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-rpc/hostname"
                    BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
                    BITCOIN_RPC_USER: $BITCOIN_RPC_USER
                    BITCOIN_RPC_PASSWORD: $BITCOIN_RPC_PASS
                    LND_REST_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-rest/hostname"
                    LND_GRPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-grpc/hostname"
                    LND_CERT_FILE: "/lnd/tls.cert"
                    LND_ADMIN_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon"
                    SHUTDOWN_SIGNAL_FILE: "/signals/shutdown"
                    REBOOT_SIGNAL_FILE: "/signals/reboot"
                    GITHUB_REPO: "runcitadel/compose"
                    VERSION_FILE: "/info.json"
                    UPDATE_STATUS_FILE: "/statuses/update-status.json"
                    UPDATE_SIGNAL_FILE: "/signals/update"
                    UPDATE_LOCK_FILE: "/statuses/update-in-progress"
                    BACKUP_STATUS_FILE: "/statuses/backup-status.json"
                    DEBUG_STATUS_FILE: "/statuses/debug-status.json"
                    TOR_PROXY_IP: "${TOR_PROXY_IP}"
                    TOR_PROXY_PORT: "9150"
                    TOR_HIDDEN_SERVICE_DIR: "/var/lib/tor"
                networks:
                    net:
                        ipv4_address: ${MANAGER_IP}
        middleware:
                container_name: middleware
                image: communitybitcoinnode/middleware:main@sha256:474de49749485d3e776ea2dd9eb70c464744b517e9b91d7b42dd682d88794760
                depends_on: [ manager, bitcoin, lnd ]
                command: ["./wait-for-node-manager.sh", "${MANAGER_IP}", "npm", "start"]
                restart: unless-stopped
                depends_on: [ manager ]
                volumes:
                        - ${PWD}/lnd:/lnd
                        - jwt-public-key:/jwt-public-key
                environment:
                    PORT: "3005"
                    BITCOIN_HOST: "${BITCOIN_IP}"
                    RPC_PORT: $BITCOIN_RPC_PORT
                    RPC_USER: $BITCOIN_RPC_USER
                    RPC_PASSWORD: $BITCOIN_RPC_PASS
                    LND_NETWORK: $BITCOIN_NETWORK
                    LND_HOST: "${LND_IP}"
                    JWT_PUBLIC_KEY_FILE: "/jwt-public-key/jwt.pem"
                    DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
                networks:
                    net:
                        ipv4_address: ${MIDDLEWARE_IP}
        neutrino-switcher:
                container_name: neutrino-switcher
                image: getumbrel/neutrino-switcher:v1.3.0@sha256:399ccea7f39129ff16c9c408f9e68a01dd4671f428273f3c3f401a8a0d2f7ddc
                depends_on: [ bitcoin, lnd ]
                restart: unless-stopped
                volumes:
                    - ${PWD}/lnd:/lnd
                    - ${PWD}/statuses:/statuses
                    - /var/run/docker.sock:/var/run/docker.sock
                environment:
                    JSONRPCURL: "http://${BITCOIN_IP}:${BITCOIN_RPC_PORT}"
                    RPCUSER: $BITCOIN_RPC_USER
                    RPCPASS: $BITCOIN_RPC_PASS
                    LND_CONTAINER_NAME: lnd
                    SLEEPTIME: 3600
                networks:
                    net:
                        ipv4_address: ${NEUTRINO_SWITCHER_IP}
        electrs:
              container_name: electrs
              image: getumbrel/electrs:v0.8.9@sha256:592fb50cdf16fa2b2e20f7c0a28d4a132c2ee636d89d4b9c24f14886763b5478
              depends_on: [ bitcoin ]
              volumes:
                - ${PWD}/bitcoin:/data/.bitcoin:ro
                - ${PWD}/electrs:/data
              restart: unless-stopped
              stop_grace_period: 5m
              ports:
                  - "50001:50001"
              networks:
                  net:
                      ipv4_address: ${ELECTRUM_IP}
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: "$NETWORK_IP/24"


volumes:
    jwt-public-key:
    jwt-private-key:
