services:
  web:
    env:
      BITCOIN_IP: ${BITCOIN_IP}
      BITCOIN_NETWORK: ${BITCOIN_NETWORK}
      BITCOIN_P2P_PORT: ${BITCOIN_P2P_PORT}
      BITCOIN_RPC_AUTH: ${BITCOIN_RPC_AUTH}
      BITCOIN_RPC_PASS: ${BITCOIN_RPC_PASS}
      BITCOIN_RPC_PORT: ${BITCOIN_RPC_PORT}
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      EXAMPLE_VALUE: ${LND_GRPC_PORT}$BITCOIN_NETWORK
      LND_GRPC_PORT: ${LND_GRPC_PORT}
      LND_IP: ${LND_IP}
      LND_REST_PORT: ${LND_REST_PORT}
    image: runcitadel/web:v0.0.1
    ports:
    - 80: 81
    volumes:
    - ${LND_DATA_DIR}:/lnd:ro
    - ${APP_DATA_DIR}/web/:/var/lib/data
version: '3.7'
